language: node_js

sudo: required

services:
  - postgresql

node_js:
    - '7.6.0'

cache:
    directories:
        - node_modules

before_script:
    - export NODE_ENV=test
    - export CXX="g++-6"
    - sleep 3
    - npm install -g yarn
    - make install
